.jshintrc
README.md
lib/storage.js
tests/storage.spec.js

This method allows the user to retrieve the list of currently saved
keys.

Implement .keys() method

---

README.md
appveyor.yml
doc/README.hbs
package.json
tests/storage.spec.js
tests/utils.spec.js

https://github.com/jviotti/electron-json-storage/issues/4
Signed-off-by: Juan Cruz Viotti <jviottidc@gmail.com>

Fix Windows tests in Appveyor

---

README.md

Corrected david-md dependency link.

Update david-md dependency link

---

README.md
lib/storage.js
tests/storage.spec.js

See: https://github.com/jviotti/electron-json-storage/issues/25

Implement `.getAll()`

---

README.md
lib/storage.js
tests/storage.spec.js

Implement `.getMany()`

---

lib/storage.js
tests/storage.spec.js

See: https://github.com/jviotti/electron-json-storage/issues/54

Include the invalid error object on "invalid data" error

---

lib/storage.js
tests/storage.spec.js

See: https://github.com/jviotti/electron-json-storage/issues/54

Ignore .DS_Store in settings directory

---

lib/storage.js

See: https://github.com/jviotti/electron-json-storage/issues/57

Get rid of ES6 features

---

lib/storage.js
package.json

This dependency causes UglifyJS issues.
See: https://github.com/jviotti/electron-json-storage/issues/57

Get rid of `exists-file`

---

CHANGELOG.md
README.md
doc/README.hbs
package.json

Update repository information

---

tests/storage.spec.js

See: https://github.com/electron-userland/electron-json-storage/issues/70

Run a serial stress testing case

---

tests/storage.spec.js

See: https://github.com/electron-userland/electron-json-storage/issues/75

test: storing and retrieving data from a key that has a colon

---

README.md
lib/storage.js
lib/utils.js
tests/storage.spec.js
tests/utils.spec.js

Minor project refactoring

---

lib/utils.js
tests/utils.spec.js

Fixes: https://github.com/electron-userland/electron-json-storage/issues/83

Convert asterisks to hyphens to about paths issues on Windows

---

README.md
lib/storage.js
lib/utils.js
package.json
tests/storage.spec.js
tests/utils.spec.js

Fixes: https://github.com/electron-userland/electron-json-storage/issues/85

Accept a custom data path in all functions

---

lib/storage.js

Fixes: https://github.com/electron-userland/electron-json-storage/issues/91

Set default value for options arguments

---

lib/utils.js
tests/storage.spec.js
tests/utils.spec.js

Allow spaces in file names

---

.travis.yml
lib/storage.js
lib/utils.js
package.json
stress/process.js
stress/start.sh
tests/storage.spec.js

Fixes: #107
Fixes: #89
Fixes: #40

Implement proper locking to avoid parallel writes conflicts

---

lib/lock.js
lib/storage.js
package.json
tests/storage.spec.js
tests/utils.spec.js

See: https://github.com/electron-userland/electron-json-storage/issues/116

Retry unlocking if EPERM

---

package.json

Fixes: https://github.com/electron-userland/electron-json-storage/issues/120

Make Electron a dev dependency

---

lib/lock.js
lib/storage.js

See: https://github.com/electron-userland/electron-json-storage/issues/116

Retry on EPERM when locking and reading

---

lib/storage.js
package-lock.json
package.json

Fixes: https://github.com/electron-userland/electron-json-storage/issues/45

Implement atomic writes

---

lib/storage.js

In some of our cases we use this package to store configuration and it's very annoying to save the file as utf-8 in every change

allow to read file that saved in other encodings then utf-8

---

README.md
lib/storage.js
package-lock.json
package.json
tests/storage.spec.js

See: https://github.com/electron-userland/electron-json-storage/issues/123

Retry write if resulting file size is zero when using validate=true

---

package-lock.json
package.json

Upgrade Electron deps

---

lib/storage.js

Adds support for JSON pretty printing, or passing other spacing parameters to JavaScript's JSON.stringify method.

Added spacing option for writing to JSON.

---

tests/storage.spec.js

See: https://github.com/electron-userland/electron-json-storage/pull/151

Add unit tests for the new prettyPrinting option

---

README.md

The README was missing this word.

Adds missing word "not"

---

CHANGELOG.md
package-lock.json
package.json

Upgrade to v4.5.0
